apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploymentszz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-serviceszz
  template:
    metadata:
      labels:
        app: test-serviceszz
    spec:
      containers:
      - name: test-serviceszz
        image: github_user_commits_service:tag1

---
apiVersion: v1
kind: Service
metadata:
  name: test-serviceszz
spec:
  selector:
    app: test-serviceszz
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000