apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-usercommits-sach30
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-commits-servicesach30
  template:
    metadata:
      labels:
        app: user-commits-servicesach30
    spec:
      containers:
      - name: user-commits-servicesach30
        image: sachinitenn/github_user_commits_service:github_user_commits_service

---
apiVersion: v1
kind: Service
metadata:
  name: user-commits-servicesach30
spec:
  selector:
    app: user-commits-servicesach30
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
