apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-changes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-changes-service
  template:
    metadata:
      labels:
        app: code-changes-service
    spec:
      containers:
      - name: code-changes-service
        image: sachinitenn/github_code_changes_service:github_code_changes_service

---
apiVersion: v1
kind: Service
metadata:
  name: code-changes-service
spec:
  selector:
    app: code-changes-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
