apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-activity-deployment
  labels:
    app: user-activity-service
    env: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-activity-service
      env: green
  template:
    metadata:
      labels:
        app: user-activity-service
        env: green
    spec:
      containers:
      - name: user-activity-service
        image: sachinitenn/github_user_activity_service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: user-activity-service
spec:
  selector:
    app: user-activity-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
